### ISSUE TITLE
Refocus2Gif

### ISSUE THREAD

**Issue by howbbig** [Vincentqyw/light-field-Processing#1]
你好，我在学习光场重聚焦的工作。
请问有refocus的代码能参考一下吗？

**Comment by Vincentqyw** [comment]
I use the refocusing code from [TAO2013](https://github.com/Vincentqyw/Depth-Estimation-Light-Field/tree/master/LF_DC)，you can refer to this [link](https://github.com/Vincentqyw/Depth-Estimation-Light-Field/blob/master/LF_DC/required/mex/REMAP2REFOCUS_mex.c) .
