### ISSUE TITLE
How to use it in my own data

### ISSUE THREAD

**Issue by sky-fly97** [Vincentqyw/light-field-Processing#3]
I want to use it in my own device, but the format is not LFP, but PNG. How can I use it in my own image

**Comment by Vincentqyw** [comment]
What kind of image do you have? 
If you have a remap image (like [this](https://vincentqin.gitee.io/blogresource-1/LightField-Toolbox/deer-zoom-in.png)), you can generate 5D LF using [`src/Remap2LF.m`](https://github.com/Vincentqyw/light-field-Processing/blob/master/src/Remap2LF.m) , then view 5D LF using `demo.m`.

**Comment by sky-fly97** [comment]
My image is like this, taken with a light field microscope~The object is a glass lens.
![1-25-5X-True-calib](https://user-images.githubusercontent.com/55578436/105717831-8d2aff00-5f5b-11eb-9f7b-7bd38850c02e.png)

**Comment by sky-fly97** [comment]
In addition, the shape of the subunits of my microlens array is square rather than circular, so the subunits of the image are all square

**Comment by Vincentqyw** [comment]
I have updated the code. You need to update the code and make a micro change to `demo.m` , changing `views=[4,4]; ` to the angluar resolution of your image. For example,  setting ` views=[4,4]; `, we will get a image like this.
![tmp](https://user-images.githubusercontent.com/18531182/105728483-2a3f6500-5f67-11eb-9f4e-0525314519d4.png)

**Comment by sky-fly97** [comment]
> I have updated the code. You need to update the code and make a micro change to `demo.m` , changing `views=[4,4]; ` to the angluar resolution of your image. For example, setting `views=[4,4];`, we will get a image like this.
> ![tmp](https://user-images.githubusercontent.com/18531182/105728483-2a3f6500-5f67-11eb-9f4e-0525314519d4.png)

Thanks， I will try it!
